In [12]:
import pandas as pd
import numpy as num
import matplotlib.pyplot as plt
import gurobipy as gp
from   gurobipy import GRB
import time
import datetime
import math
import csv
import os
import warnings
import re
import collections

import my_functions_const as fc
import my_functions as f

## Get the fixed inputs

In [3]:
%run ./Execution_fixedinputs_ATJ.ipynb 
T

True
True
[310, 311, 312, 313, 314, 316, 317, 330, 331, 332, 333, 334, 336, 337, 338, 339, 350, 351, 352, 353, 354, 360, 361, 363, 370, 371, 373, 374, 375, 376]
[310, 311, 312, 313, 314, 316, 317, 330, 331, 332, 333, 334, 336, 337, 338, 339, 350, 351, 352, 353, 354, 360, 361, 363, 370, 371, 373, 374, 375, 376]

144

In [13]:
%run ./Data_Validation.ipynb

FileNotFoundError: [Errno 2] No such file or directory: 'results/VolIn_3.csv'

FileNotFoundError: [Errno 2] No such file or directory: 'results/VolIn_3.csv'

## Get the data inputs

In [38]:
with open('results/VolIn_3.csv', 'r') as f:
    reader = csv.reader(f)
    data1 = {}
    for row in reader:
        data1[row[0]] = eval(row[1])
VolIn = data1 

with open('results/VolOut_3.csv', 'r') as f:
    reader = csv.reader(f)
    data1 = {}
    for row in reader:
        data1[row[0]] = eval(row[1])
VolOut = data1    

with open('results/VolExist_3.csv', 'r') as f:
    reader = csv.reader(f)
    data1 = {}
    for row in reader:
        data1[row[0]] = eval(row[1])
VolExist = data1   

tickets = pd.read_csv('results/tickets_3.csv')

## Generate the index

In [6]:
index = fc.function_index(Time, topo_i, topo_o)

## Run the Sequence

In [ ]:
ID = 1
# Inputs for ID = 1 #Good: 031, 051, 071 #Bad: 061
cycle = '031'
CycleVolIn2   = VolIn[cycle]
CycleVolOut2  = VolOut[cycle]
CycleVolExist  = VolExist[cycle]
CycleVolExist_ = VolExist[cycle]

# temp_ = {}    
# for tank in CycleVolExist_:
#     for prod in CycleVolExist_[tank]:
#         if prod in temp_:
#             temp_[prod] = temp_[prod] + CycleVolExist_[tank][prod]
#         else:
#             temp_[prod] = CycleVolExist_[tank][prod]
# temp_ = {k:v for k,v in sorted(temp_.items())}
# temp_

# temp_ = {}    
# for tank in CycleVolOut2:
#     for prod in CycleVolOut2[tank]:
#         if prod in temp_:
#             temp_[prod] = temp_[prod] + CycleVolOut2[tank][prod]
#         else:
#             temp_[prod] = CycleVolOut2[tank][prod]
# temp_ = {k:v for k,v in sorted(temp_.items())}
# temp_

# temp_ = {}    
# for tank in CycleVolIn2:
#     for prod in CycleVolIn2[tank]:
#         if prod in temp_:
#             temp_[prod] = temp_[prod] + CycleVolIn2[tank][prod]
#         else:
#             temp_[prod] = CycleVolIn2[tank][prod]
# temp_ = {k:v for k,v in sorted(temp_.items())}
# temp_

# df = pd.read_csv("results/opt_schedule_1.csv")

# # Step 1: Calculate flow in
# a = df[df['Line'].isin(['01', '02'])]
# a = a.groupby(['Tank', 'Product']).agg({'Volume':'sum'}).reset_index()
# b = {}
# for index, row in a.iterrows():
#     tank = row['Tank']
#     product = row['Product']
#     volume = row['Volume']
#     if tank not in b:
#         b[tank] = {}
#     b[tank][product] = volume
# temp_In = b

# # Step 2: Calculate flow out
# a = df[~df['Line'].isin(['01', '02'])]
# a = a.groupby(['Tank', 'Product']).agg({'Volume':'sum'}).reset_index()
# b = {}
# for index, row in a.iterrows():
#     tank = row['Tank']
#     product = row['Product']
#     volume = row['Volume']
#     if tank not in b:
#         b[tank] = {}
#     b[tank][product] = volume
# temp_Out = b

# # Step 3: Build the dictionary
# keys = list(temp_Out.keys()) + list(temp_In.keys()) + list(CycleVolExist.keys())
# keys = list(set(keys))

# temp1 = {}
# for key in keys:
#     if key in CycleVolExist:
#         temp1[key] = CycleVolExist[key]
#     if key in temp_In:
#         temp1[key] = temp_In[key]
#     if key in temp_Out:
#         temp1[key] = temp_Out[key]     

# temp2 = {}
# for key, value in temp1.items():
#     temp2[key] = {k: 0 for k in value}
  
# for key in temp2:
#     if key in CycleVolExist:
#         a = list(CycleVolExist[key].values())[0]
#     else: 
#         a = 0
#     if key in temp_In:
#         b = list(temp_In[key].values())[0]
#     else: 
#         b = 0
#     if key in temp_Out:
#         c = list(temp_Out[key].values())[0]
#     else: 
#         c = 0  
    
#     for p in temp2[key]:
#         temp2[key][p] = a + b - c 
                  

# # for key, value in temp2.items():
# #     if value < 0:
# #         temp2[key] = 0

# temp_CycleVolExist = temp2


# # temp_ = {}    
# # for tank in temp_CycleVolExist:
# #     for prod in temp_CycleVolExist[tank]:
# #         if prod in temp_:
# #             temp_[prod] = temp_[prod] + temp_CycleVolExist[tank][prod]
# #         else:
# #             temp_[prod] = temp_CycleVolExist[tank][prod]
# # temp_ = {k:v for k,v in sorted(temp_.items())}



# temp_CycleVolExist
# temp_Out

# temp_ = {}    
# for tank in CycleVolExist_:
#     for prod in CycleVolExist_[tank]:
#         if prod in temp_:
#             temp_[prod] = temp_[prod] + CycleVolExist_[tank][prod]
#         else:
#             temp_[prod] = CycleVolExist_[tank][prod]
# temp_ = {k:v for k,v in sorted(temp_.items())}
# print(temp_)

# temp_ = {}    
# for tank in CycleVolIn2:
#     for prod in CycleVolIn2[tank]:
#         if prod in temp_:
#             temp_[prod] = temp_[prod] + CycleVolIn2[tank][prod]
#         else:
#             temp_[prod] = CycleVolIn2[tank][prod]
# temp_ = {k:v for k,v in sorted(temp_.items())}
# print(temp_)

# temp_ = {}    
# for tank in CycleVolOut2:
#     for prod in CycleVolOut2[tank]:
#         if prod in temp_:
#             temp_[prod] = temp_[prod] + CycleVolOut2[tank][prod]
#         else:
#             temp_[prod] = CycleVolOut2[tank][prod]
# temp_ = {k:v for k,v in sorted(temp_.items())}
# print(temp_)

In [ ]:
import my_functions as f
data     = f.function_model_stage1(ID, index, CycleVolIn2, CycleVolOut2, CycleVolExist, Bounds, Capacity, Tanks, T, Time)

In [ ]:
import my_functions as f
ID = 1
schedule = f.function_model_stage2(ID, index, CycleVolIn2, CycleVolOut2, CycleVolExist, Bounds, Capacity, Tanks, T, Time)

In [ ]:
ID = 2

# External Inputs
cycle = '041' 
CycleVolIn2   = VolIn[cycle]
CycleVolOut2  = VolOut[cycle]

# Feed Input
with open("results/opt_CycleVolExist_1.csv", "r") as file:
    reader = csv.reader(file)
    next(reader) # skip header row
    my_dict = {int(rows[0]): eval(rows[1]) for rows in reader} 
    
CycleVolExist = my_dict

In [ ]:
data     = f.function_model_stage1(ID, index, CycleVolIn2, CycleVolOut2, CycleVolExist, Bounds, Capacity, Tanks, T, Time)

In [ ]:
schedule = f.function_model_stage2(ID, index, CycleVolIn2, CycleVolOut2, CycleVolExist, Bounds, Capacity, Tanks, T, Time)

In [ ]:
ID = 3

# External Inputs
cycle = '051' 
CycleVolIn2    = VolIn[cycle]
CycleVolOut2   = VolOut[cycle]
CycleVolExist_ = VolExist[cycle]

# Feed Input
with open("results/opt_CycleVolExist_2.csv", "r") as file:
    reader = csv.reader(file)
    next(reader) # skip header row
    my_dict = {int(rows[0]): eval(rows[1]) for rows in reader} 
    
CycleVolExist = my_dict    

temp_ = {}    
for tank in CycleVolExist_:
    for prod in CycleVolExist_[tank]:
        if prod in temp_:
            temp_[prod] = temp_[prod] + CycleVolExist_[tank][prod]
        else:
            temp_[prod] = CycleVolExist_[tank][prod]            
temp_ = {k:v for k,v in sorted(temp_.items())}

temp = {}    
for tank in CycleVolExist:
    for prod in CycleVolExist[tank]:
        if prod in temp:
            temp[prod] = temp[prod] + CycleVolExist[tank][prod]
        else:
            temp[prod] = CycleVolExist[tank][prod]
temp = {k:v for k,v in sorted(temp.items())}

print("Original", temp_)
print("***")
print("Processed", temp)

In [ ]:
import my_functions as f
data     = f.function_model_stage1(ID, index, CycleVolIn2, CycleVolOut2, CycleVolExist, Bounds, Capacity, Tanks, T, Time)

In [ ]:
schedule = f.function_model_stage2(ID, index, CycleVolIn2, CycleVolOut2, CycleVolExist, Bounds, Capacity, Tanks, T, Time)

In [7]:
ID = 4

# External Inputs
cycle = '061' 
CycleVolIn2   = VolIn[cycle]
CycleVolOut2  = VolOut[cycle]

CycleVolIn2['01'] = {'A': 1403, 'D': 202}

# # Feed Input
with open("results/opt_CycleVolExist_3.csv", "r") as file:
    reader = csv.reader(file)
    next(reader) # skip header row
    my_dict = {int(rows[0]): eval(rows[1]) for rows in reader} 

CycleVolExist = my_dict 

CycleVolExist_ = CycleVolExist
temp_ = {}    
for tank in CycleVolExist_:
    for prod in CycleVolExist_[tank]:
        if prod in temp_:
            temp_[prod] = temp_[prod] + CycleVolExist_[tank][prod]
        else:
            temp_[prod] = CycleVolExist_[tank][prod]
temp_ = {k:v for k,v in sorted(temp_.items())}
print(temp_)

temp_ = {}    
for tank in CycleVolIn2:
    for prod in CycleVolIn2[tank]:
        if prod in temp_:
            temp_[prod] = temp_[prod] + CycleVolIn2[tank][prod]
        else:
            temp_[prod] = CycleVolIn2[tank][prod]
temp_ = {k:v for k,v in sorted(temp_.items())}
print(temp_)

temp_ = {}    
for tank in CycleVolOut2:
    for prod in CycleVolOut2[tank]:
        if prod in temp_:
            temp_[prod] = temp_[prod] + CycleVolOut2[tank][prod]
        else:
            temp_[prod] = CycleVolOut2[tank][prod]
temp_ = {k:v for k,v in sorted(temp_.items())}
print(temp_)

{'54': 21, '62': 99, 'A': 72, 'D': 140}
{'54': 345, '62': 899, 'A': 1403, 'D': 202}
{'54': 319, '62': 818, 'A': 1272, 'D': 211}

In [10]:
data     = f.function_model_stage1(ID, index, CycleVolIn2, CycleVolOut2, CycleVolExist, Bounds, Capacity, Tanks, T, Time)

Set parameter CloudAccessID
Set parameter CloudSecretKey
Set parameter CloudPool to value "842451-default"
Set parameter LicenseID
Waiting for cloud server to start (pool 842451-default)...
Starting...
Starting...
Starting...
Compute Server job ID: 4c3c3cbc-f5b8-410a-a0cb-2c0a7c7cf74d
Capacity available on '842451-default' cloud pool - connecting...
Established HTTPS encrypted connection
Set parameter TimeLimit to value 480
Gurobi Optimizer version 9.5.1 build v9.5.1rc2 (win64)
Gurobi Compute Server Worker version 9.5.1 build v9.5.1rc2 (linux64)
Thread count: 8 physical cores, 16 logical processors, using up to 16 threads
Optimize a model with 2581905 rows, 76753 columns and 5271896 nonzeros
Model fingerprint: 0x7ea580e6
Variable types: 38161 continuous, 38592 integer (38592 binary)
Coefficient statistics:
  Matrix range     [1e+00, 3e+01]
  Objective range  [1e+00, 1e+00]
  Bounds range     [1e+00, 2e+02]
  RHS range        [1e+00, 2e+03]

Starting distributed worker jobs...

Using Compute Server as first worker
Started distributed worker on https://ip-10-0-59-48:61000
Started distributed worker on https://ip-10-0-62-95:61000
Started distributed worker on https://ip-10-0-53-70:61000
Started distributed worker on https://ip-10-0-59-95:61000
Started distributed worker on https://ip-10-0-63-209:61000

Distributed MIP job count: 6

    Nodes    |    Current Node    |     Objective Bounds      |     Work
 Expl Unexpl |  Obj  Depth IntInf | Incumbent    BestBd   Gap | ParUtil Time

     0     0                               -   97.00000      -   99%   40s
     0     0                               -   97.00000      -   99%   55s
     0     0                               -   97.00000      -   99%   70s
     0     0                               -   97.00000      -   99%   85s
     0     0                               -   97.00000      -   99%  100s
     0     0                               -   97.00000      -   99%  115s
     0     0                               -   97.00000      -   99%  130s
     0     0                               -   97.00000      -   99%  145s
     0     0                               -   97.00000      -   99%  160s
     0     0                               -   97.00000      -   99%  176s
     0     0                               -   97.00000      -   99%  191s
     0     0                               -   97.00000      -   99%  206s
     0     0                               -   97.00000      -   99%  221s
     0     0                               -   97.00000      -   99%  236s
H    0                            97.0000000   97.00000  0.00%        247s
     0     0                        97.00000   97.00000  0.00%   99%  247s
     6     5   97.00000    0   49   97.00000   97.00000  0.00%   99%  370s

Explored 6 nodes (910516 simplex iterations) in 370.64 seconds (344.09 work units)
Distributed MIP job count: 6

Solution count 1: 97

Optimal solution found (tolerance 1.00e-04)
Best objective 9.700000000000e+01, best bound 9.700000000000e+01, gap 0.0000%

In [11]:
schedule = f.function_model_stage2(ID, index, CycleVolIn2, CycleVolOut2, CycleVolExist, Bounds, Capacity, Tanks, T, Time)

Set parameter TimeLimit to value 720
Gurobi Optimizer version 9.5.1 build v9.5.1rc2 (win64)
Gurobi Compute Server Worker version 9.5.1 build v9.5.1rc2 (linux64)
Thread count: 8 physical cores, 16 logical processors, using up to 16 threads
Optimize a model with 226471 rows, 235214 columns and 671514 nonzeros
Model fingerprint: 0x449a6295
Model has 43043 general constraints
Variable types: 38161 continuous, 197053 integer (38797 binary)
Coefficient statistics:
  Matrix range     [1e+00, 3e+01]
  Objective range  [1e+00, 1e+00]
  Bounds range     [1e+00, 2e+02]
  RHS range        [1e+00, 2e+03]

Starting distributed worker jobs...

Using Compute Server as first worker
Started distributed worker on https://ip-10-0-59-48:61000
Started distributed worker on https://ip-10-0-62-95:61000
Started distributed worker on https://ip-10-0-59-95:61000
Started distributed worker on https://ip-10-0-63-209:61000
Started distributed worker on https://ip-10-0-53-70:61000

Distributed MIP job count: 6

    Nodes    |    Current Node    |     Objective Bounds      |     Work
 Expl Unexpl |  Obj  Depth IntInf | Incumbent    BestBd   Gap | ParUtil Time

     0     0                               -    0.00000      -   99%    3s
     0     0                               -    1.00000      -   99%    4s
     0     0                               -    1.00000      -   99%   19s
     0     0                               -    1.00000      -   99%   34s
     0     0                               -    1.00000      -   99%   49s
     0     0                               -    1.00000      -   99%   64s
     0     0                               -    1.00000      -   99%   79s
     0     0                               -    1.00000      -   99%   94s
     0     0                               -    1.00000      -   99%  109s
     0     0    1.00000    0  952          -    1.00000      -   99%  124s
     0     0    1.00000    0  786          -    1.00000      -   99%  139s
     0     0    1.00000    0  732          -    1.00000      -   99%  154s
     0     0    1.00000    0  576          -    1.00000      -   99%  169s
     0     0    1.00000    0  436          -    1.00000      -   99%  184s
     0     0    1.00000    0  639          -    1.00000      -   99%  199s
     0     0    1.00000    0  639          -    1.00000      -   99%  214s
     0     2    1.00000    0  639          -    1.00000      -   99%  221s
     2     4    1.00000    1 1005          -    1.00000      -   99%  225s
     4     8    1.00000    0  639          -    1.00000      -   99%  230s
     4    10    1.00000    0  618          -    1.00000      -   99%  240s
     6    12    1.00000    1  723          -    1.00000      -   99%  245s
     7    16    1.00000    2  828          -    1.00000      -   99%  250s
    13    24    1.00000    3 1477          -    1.00000      -   99%  255s
    23    32    1.00000    4 1743          -    1.00000      -   99%  260s
    30    40    1.00000    3 1835          -    1.00000      -   99%  265s
    30    42    1.00000    0 1109          -    1.00000      -   99%  275s
    32    44    1.00000    0 1083          -    1.00000      -   99%  280s
    42    56    1.00000    4 1556          -    1.00000      -   99%  285s
    46    64    1.00000    0 1082          -    1.00000      -   99%  290s
    67    80    1.00000    5 1814          -    1.00000      -   99%  295s
    97   112    1.00000    4 1646          -    1.00000      -   99%  300s
   102   120    1.15706    6 1439          -    1.00000      -   99%  305s
   108   128    1.00000    5  950          -    1.00000      -   99%  320s
   122   141    1.00953    6 1301          -    1.00000      -   99%  325s
   128   149    1.00000    6  839          -    1.00000      -   99%  330s
   143   200    1.00000    9  672          -    1.00000      -   99%  345s
   152   212    1.00000    1  982          -    1.00000      -   99%  350s
   157   216    1.00000    2 1139          -    1.00000      -   99%  355s
   168   246    1.00000    8  693          -    1.00000      -   99%  360s
   175   260    1.00000    7 2142          -    1.00000      -   99%  365s
   225   379    1.00000    4 1086          -    1.00000      -   99%  370s
   253   407    1.00000    5 1159          -    1.00000      -   99%  375s
   262   415    1.00000    6 1042          -    1.00000      -   99%  380s
   370   488    1.00000   10  693          -    1.00000      -   99%  390s
   401   522    1.00000    6 1130          -    1.00000      -   99%  400s
   422   566    1.00000    8  936          -    1.00000      -   99%  410s
   621   798    1.00000   12  801          -    1.00000      -   99%  425s
   773   938    1.00000   14  915          -    1.00000      -   99%  430s
   919  1154    2.00000   20  747          -    1.00000      -   99%  445s
  1292  1647    1.02933   24  468          -    1.00000      -   99%  450s
  1302  1657    1.00000    0  781          -    1.00000      -   99%  455s
  1641  2055    2.00000   19  745          -    1.00000      -   99%  460s
* 2012                             4.0000000    1.00000  75.0%        467s
  2492  2621    1.24897   75 2290    4.00000    1.00000  75.0%   99%  470s
  3503  3534     cutoff              4.00000    1.00000  75.0%   99%  485s
  4234  3881    1.00000    6  584    4.00000    1.00000  75.0%   99%  495s
H 5217                             2.0000000    1.00000  50.0%        495s
  5496  3737    3.00000  137   74    2.00000    1.00000  50.0%   99%  500s
  5771  4181    2.11905   81 1008    2.00000    1.00000  50.0%   99%  505s
  5803  4213   14.01020  160  611    2.00000    1.00000  50.0%   99%  510s
  6511  4519    3.00000  183  348    2.00000    1.00000  50.0%   99%  520s
  7050  3698    2.00000   51  664    2.00000    1.00000  50.0%   99%  530s
  7536  4220    3.00000  113  682    2.00000    1.00000  50.0%   99%  540s
  8328  3874     cutoff              2.00000    1.00000  50.0%   99%  545s
  9096  4185 infeasible              2.00000    1.00000  50.0%   99%  550s
  9492  4513    1.02304  140 1346    2.00000    1.00000  50.0%   99%  560s
H 9761                             1.0000000    1.00000  0.00%        561s
  9762  3932                         1.00000    1.00000  0.00%   99%  561s

Instance 2 was solved

Explored 11105 nodes (16189097 simplex iterations) in 618.35 seconds (705.15 work units)
Distributed MIP job count: 6

Solution count 7: 1 2 3 ... 9

Optimal solution found (tolerance 1.00e-04)
Best objective 1.000000000000e+00, best bound 1.000000000000e+00, gap 0.0000%

In [137]:
schedule_1 = pd.read_csv("results/opt_schedule_1.csv")
schedule_2 = pd.read_csv("results/opt_schedule_2.csv")
schedule_3 = pd.read_csv("results/opt_schedule_3.csv")
schedule_4 = pd.read_csv("results/opt_schedule_4.csv")

ID = 4
a = schedule_4
a['Ticket'] = range(0, len(a))

#-------------------------------------------------------------------------------------------------------------                                            
# Set the Mode 
#
def flag_df(df):
    if (df['Line'] in ['01', '02']):
        return 'In'
    else:
        return 'Out'
a['Mode']   = a.apply(flag_df, axis = 1)

#-------------------------------------------------------------------------------------------------------------                                            
# 
#
a['Start_Date_Time']  = pd.to_datetime(a['Start_Date_Time'])
a['Finish_Date_Time'] = pd.to_datetime(a['Finish_Date_Time'])
a['Repetition'] = (a['Finish_Date_Time'] - a['Start_Date_Time'])/ num.timedelta64(1, 'm') 
a = a.loc[a.index.repeat(a['Repetition'])]

a['Volume_unit_time'] = a['Volume']/a['Repetition']
a['Temp'] = 1
a['Order'] = a[['Tank', 'Line', 'Ticket', 'Temp']].groupby(['Tank', 'Line', 'Ticket']).cumsum() - 1
a['Time'] = a['Start_Date_Time'] + a['Order'] * datetime.timedelta(minutes=1) 
a['Time_hr'] = a['Time'].dt.floor('h')

#-------------------------------------------------------------------------------------------------------------                                            
# 
#
def flag_in(df):
    if (df['Mode'] in ['In']):
        return df['Volume'] / df['Repetition'] 
    else:
        return 0
a['Vol_In'] = a.apply(flag_in, axis = 1)

def flag_out(df):
    if (df['Mode'] in ['Out']):
        return df['Volume'] / df['Repetition'] 
    else:
        return 0
a['Vol_Out'] = a.apply(flag_out, axis = 1)

a['Vol'] = a['Vol_In'] + a['Vol_Out']
a['Vol'] = a['Volume_Exists'] + a['Vol']

#-------------------------------------------------------------------------------------------------------------                                            
# 
#
b = a.groupby(['Tank', 'Time_hr']).agg({'Volume_Exists':'max', 'Vol_In': 'sum', 'Vol_Out': 'sum'})
b = b.reset_index()

col = b[['Tank', 'Time_hr', 'Vol_In']].groupby(['Tank']).cumsum(skipna=False)
b['Vol_In_cum'] = col
col = b[['Tank', 'Time_hr', 'Vol_Out']].groupby(['Tank']).cumsum(skipna=False)
b['Vol_Out_cum'] = col
b['Vol_cum'] = b['Volume_Exists'] + b['Vol_In_cum'] - b['Vol_Out_cum']

b = b.groupby(['Tank']).agg({'Vol_cum':'max'})
b.to_csv("results/metrics_max_" + str(ID) + ".csv")
b

         Vol_cum
Tank
312   148.000000
332     3.000000
337    92.500000
339   103.700000
350   273.000000
351    -8.700000
352    -1.548387
376   133.630435

In [128]:
s0 = tickets[['Line', 'Product', 'Tank']]
s1 = schedule_1[['Line', 'Product', 'Tank']]
s2 = schedule_2[['Line', 'Product', 'Tank']]
s3 = schedule_3[['Line', 'Product', 'Tank']]
s4 = schedule_4[['Line', 'Product', 'Tank']]
s0 = pd.concat([s0, s1, s2, s3, s4])
s0 = s0.groupby(['Line', 'Product', 'Tank']).count()

In [139]:
pd.set_option('display.max_rows', None)

#----------------------------------------------------------------------------
#
#
schedule = tickets.loc[tickets['Cycle'] == 31]
s1 = schedule.groupby(['Line', 'Product', 'Tank']).agg({'Volume':'sum'})
s1[["Volume"]] = 1000 * s1[["Volume"]]

schedule = tickets.loc[tickets['Cycle'] == 41]
s2 = schedule.groupby(['Line', 'Product', 'Tank']).agg({'Volume':'sum'})
s2[["Volume"]] = 1000 * s2[["Volume"]]

schedule = tickets.loc[tickets['Cycle'] == 51]
s3 = schedule.groupby(['Line', 'Product', 'Tank']).agg({'Volume':'sum'})
s3[["Volume"]] = 1000 * s3[["Volume"]]

schedule = tickets.loc[tickets['Cycle'] == 61]
s4 = schedule.groupby(['Line', 'Product', 'Tank']).agg({'Volume':'sum'})
s4[["Volume"]] = 1000 * s4[["Volume"]]

m = pd.merge(s0, s1, how = "left", on=['Line', 'Product', 'Tank'])
m = pd.merge(m,  s2, how = "left", on=['Line', 'Product', 'Tank'])
m = pd.merge(m,  s3, how = "left", on=['Line', 'Product', 'Tank'])
m = pd.merge(m,  s4, how = "left", on=['Line', 'Product', 'Tank'])

#----------------------------------------------------------------------------
#
#
schedule = schedule_1
t1 = schedule.groupby(['Line', 'Product', 'Tank']).agg({'Volume':'sum'})
t1[["Volume"]] = 1000 * t1[["Volume"]]

schedule = schedule_2
t2 = schedule.groupby(['Line', 'Product', 'Tank']).agg({'Volume':'sum'})
t2[["Volume"]] = 1000 * t2[["Volume"]]

schedule = schedule_3
t3 = schedule.groupby(['Line', 'Product', 'Tank']).agg({'Volume':'sum'})
t3[["Volume"]] = 1000 * t3[["Volume"]]

schedule = schedule_4
t4 = schedule.groupby(['Line', 'Product', 'Tank']).agg({'Volume':'sum'})
t4[["Volume"]] = 1000 * t4[["Volume"]]

m = pd.merge(m, t1, how = "left", on=['Line', 'Product', 'Tank'])
m = pd.merge(m, t2, how = "left", on=['Line', 'Product', 'Tank'])
m = pd.merge(m, t3, how = "left", on=['Line', 'Product', 'Tank'])
m = pd.merge(m, t4, how = "left", on=['Line', 'Product', 'Tank'])

#----------------------------------------------------------------------------
#
#
m

                   Volume_x  Volume_y  Volume_x  Volume_y   Volume_x  \
Line Product Tank
01   A       310        NaN       NaN       NaN       NaN        NaN
             311   107906.0       NaN  122600.0       NaN        NaN
             313        NaN  134613.0  207255.0       NaN        NaN
             314        NaN  108011.0  107634.0  118903.0        NaN
             317   295889.0  192213.0  248766.0  115908.0        NaN
             330   176260.0  335747.0  280194.0  194978.0        NaN
             331   178437.0  259915.0   75438.0  105815.0        NaN
             332   104922.0  104486.0       NaN  104814.0        NaN
             333   212731.0  100274.0       NaN  101852.0        NaN
             334   152644.0       NaN       NaN  151875.0        NaN
             336   109963.0  107641.0       NaN  108301.0        NaN
             338    79248.0  148615.0  149183.0       NaN        NaN
             339        NaN  157985.0  152430.0       NaN  1425000.0
     D       312    81876.0  101201.0  111500.0  116576.0   253900.0
             316    83725.0   58185.0   47989.0   38155.0        NaN
             337    46554.0   30114.0   81511.0   46769.0        NaN
02   54      350    21099.0   21088.0   21080.0   21091.0        NaN
             351    32679.0   32294.0   32294.0   32646.0   396000.0
             352    79049.0   80064.0   29560.0   80064.0        NaN
             353   108547.0   60000.0   34851.0  108552.0        NaN
             354    82626.0   83653.0  103874.0  102148.0        NaN
             370        NaN   47901.0   47341.0       NaN        NaN
     62      360    54168.0   59643.0   59643.0  118807.0   365000.0
             361   113374.0  112723.0  226384.0  210505.0        NaN
             371   135388.0  264432.0  272366.0  117951.0        NaN
             373    62057.0  144585.0  255573.0  286869.0        NaN
             374        NaN  197464.0  103534.0  164868.0        NaN
             376        NaN       NaN       NaN       NaN        NaN
13   54      350        NaN       NaN       NaN       NaN        NaN
             353     6000.0       NaN       NaN   28500.0        NaN
             370        NaN   29000.0       NaN       NaN     6000.0
     62      360        NaN   59643.0   59643.0       NaN    76000.0
             361        NaN       NaN       NaN  115959.0        NaN
             373        NaN   22998.0       NaN   17041.0        NaN
             374    57640.0   33359.0   42857.0       NaN        NaN
             376        NaN       NaN       NaN       NaN        NaN
     A       310        NaN       NaN       NaN       NaN        NaN
             317        NaN       NaN       NaN       NaN     2000.0
             332        NaN       NaN       NaN       NaN        NaN
             339        NaN       NaN       NaN       NaN        NaN
     D       337        NaN       NaN       NaN       NaN        NaN
14   62      360        NaN       NaN       NaN   59000.0    33200.0
             361        NaN       NaN       NaN       NaN        NaN
             371    23540.0       NaN       NaN       NaN        NaN
             373        NaN       NaN   67500.0       NaN        NaN
             374        NaN   49500.0       NaN       NaN        NaN
             376        NaN       NaN       NaN       NaN        NaN
     A       310        NaN       NaN       NaN       NaN        NaN
             311        NaN       NaN   22100.0    5000.0        NaN
             314        NaN    5000.0       NaN    3488.0        NaN
             317   133949.0  122500.0    5000.0       NaN        NaN
             330        NaN       NaN       NaN  116512.0        NaN
             331        NaN       NaN  105900.0       NaN        NaN
             334        NaN       NaN       NaN       NaN        NaN
             336    10051.0       NaN       NaN       NaN        NaN
             339        NaN       NaN       NaN       NaN   182000.0
     D       312        NaN   29500.0       NaN   13663.0        NaN
             316        NaN       NaN       NaN   24837.0     2000.0
             337        NaN       NaN   32500.0       NaN        NaN
15   A       310        NaN       NaN       NaN       NaN        NaN
             311        NaN       NaN   41981.0       NaN        NaN
             313        NaN       NaN  127885.0       NaN        NaN
             314        NaN       NaN  107634.0  186045.0        NaN
             317   134893.0       NaN       NaN       NaN        NaN
             330    60607.0       NaN       NaN       NaN        NaN
             331        NaN  289500.0       NaN       NaN        NaN
             332        NaN       NaN       NaN       NaN        NaN
             333        NaN       NaN       NaN       NaN        NaN
             336        NaN       NaN       NaN       NaN        NaN
             339        NaN       NaN       NaN       NaN   210000.0
     D       312    79000.0       NaN   63000.0   48070.0    85000.0
             316        NaN   78500.0       NaN       NaN        NaN
             337        NaN       NaN       NaN   24430.0        NaN
16   54      350    21099.0       NaN   13597.0    7469.0   134000.0
             351    32679.0   31107.0   32294.0   32294.0        NaN
             352    72746.0   80064.0   60064.0   80064.0        NaN
             353        NaN  103548.0   16872.0   80058.0        NaN
             354        NaN       NaN  103874.0   35615.0        NaN
17   62      360        NaN       NaN       NaN       NaN        NaN
             361        NaN       NaN       NaN       NaN        NaN
             373        NaN       NaN       NaN   58632.0        NaN
             374        NaN   48142.0       NaN  164868.0        NaN
             376        NaN       NaN       NaN       NaN        NaN
     A       310        NaN       NaN       NaN       NaN        NaN
             313        NaN       NaN       NaN  161278.0        NaN
             317        NaN       NaN       NaN       NaN        NaN
             330        NaN  116111.0   52860.0    5000.0        NaN
             331    28016.0  165890.0       NaN       NaN        NaN
             333        NaN       NaN       NaN   84722.0        NaN
             334        NaN       NaN       NaN       NaN        NaN
             336    48060.0       NaN       NaN       NaN        NaN
             338    79248.0       NaN       NaN       NaN        NaN
             339        NaN       NaN       NaN       NaN   170000.0
     D       316        NaN       NaN       NaN   17500.0        NaN
             337        NaN       NaN       NaN       NaN        NaN
18   54      350        NaN       NaN       NaN       NaN        NaN
             351        NaN       NaN       NaN       NaN        NaN
             352        NaN       NaN   20000.0       NaN    21000.0
             354    11500.0    5000.0       NaN    5500.0        NaN
             370        NaN       NaN       NaN       NaN        NaN
     62      360    59031.0       NaN   13145.0       NaN        NaN
             361        NaN       NaN  113192.0       NaN        NaN
             371        NaN  105927.0  110663.0   73263.0        NaN
             373        NaN   91458.0       NaN   89023.0        NaN
             374        NaN   37115.0       NaN   88214.0        NaN
             376        NaN       NaN       NaN       NaN    60000.0
     A       310        NaN       NaN       NaN       NaN        NaN
             311        NaN       NaN       NaN       NaN        NaN
             313        NaN       NaN    8000.0       NaN        NaN
             314        NaN   10500.0       NaN       NaN        NaN
             317    10000.0       NaN       NaN       NaN        NaN
             330   115653.0       NaN   25364.0   91075.0        NaN
             331   106072.0       NaN       NaN  100900.0        NaN
             332    97422.0       NaN       NaN  104486.0        NaN
             333        NaN       NaN       NaN   86539.0        NaN
             334        NaN       NaN       NaN       NaN        NaN
             336    51852.0  107523.0       NaN       NaN        NaN
             338        NaN  148615.0  148615.0       NaN        NaN
             339        NaN  155862.0  157521.0       NaN   449000.0
     D       312    37651.0   14500.0       NaN       NaN        NaN
             316     5349.0       NaN       NaN       NaN        NaN
             337        NaN       NaN   28000.0   23500.0    43000.0
19   62      360        NaN       NaN       NaN       NaN    84200.0
             361        NaN       NaN       NaN       NaN        NaN
             373        NaN       NaN       NaN   25000.0        NaN
             376        NaN       NaN       NaN       NaN        NaN
     A       310    82919.0       NaN       NaN       NaN        NaN
             311   108115.0       NaN       NaN       NaN        NaN
             313        NaN       NaN       NaN  129489.0        NaN
             317        NaN       NaN  289601.0   96727.0        NaN
             330        NaN       NaN       NaN       NaN        NaN
             331        NaN    3915.0       NaN       NaN        NaN
             332        NaN  104486.0       NaN       NaN        NaN
             333   197466.0  194237.0       NaN       NaN        NaN
             334        NaN  104362.0  104399.0   58264.0        NaN
             339        NaN       NaN       NaN       NaN   389000.0
     D       312        NaN   45000.0       NaN   47000.0    56000.0
             316        NaN       NaN   65000.0       NaN        NaN
             337    55500.0       NaN       NaN       NaN        NaN
1A   A       310        NaN       NaN       NaN       NaN        NaN
             311        NaN       NaN   37500.0       NaN        NaN
             314        NaN       NaN       NaN       NaN        NaN
             317    52000.0   25000.0       NaN       NaN        NaN
             330        NaN   67500.0       NaN   40038.0        NaN
             333        NaN       NaN       NaN       NaN        NaN
             339        NaN       NaN       NaN       NaN   132000.0
     D       312        NaN    7500.0       NaN    9500.0    11000.0
             316        NaN       NaN    7500.0       NaN        NaN
             337     9000.0       NaN       NaN       NaN        NaN
20   54      350        NaN       NaN       NaN       NaN    42000.0
             352        NaN       NaN       NaN       NaN        NaN
             354    35000.0   31094.0       NaN   47500.0        NaN
             370        NaN   18906.0   37500.0       NaN        NaN
     62      360        NaN   42170.0       NaN       NaN        NaN
             361    29281.0       NaN       NaN       NaN        NaN
             371        NaN       NaN       NaN   92500.0        NaN
             373        NaN   18390.0   65612.0       NaN        NaN
             374        NaN       NaN       NaN       NaN        NaN
             376        NaN       NaN       NaN       NaN    32500.0
2A   62      360        NaN       NaN       NaN       NaN   108000.0
             361        NaN       NaN       NaN       NaN        NaN
             371    12500.0       NaN       NaN       NaN        NaN
             373        NaN   32500.0    2500.0   32500.0        NaN
             376        NaN       NaN       NaN       NaN        NaN

                    Volume_y   Volume_x   Volume_y
Line Product Tank
01   A       310         NaN  1357000.0        NaN
             311         NaN        NaN        NaN
             313         NaN        NaN        NaN
             314         NaN        NaN        NaN
             317         NaN        NaN        NaN
             330         NaN        NaN        NaN
             331         NaN        NaN        NaN
             332         NaN        NaN        NaN
             333         NaN        NaN        NaN
             334         NaN        NaN        NaN
             336         NaN        NaN        NaN
             338         NaN        NaN        NaN
             339   1750000.0        NaN  1503000.0
     D       312    225000.0        NaN   275000.0
             316         NaN        NaN        NaN
             337         NaN   325000.0        NaN
02   54      350    330000.0   269000.0   345000.0
             351         NaN        NaN        NaN
             352         NaN        NaN        NaN
             353         NaN        NaN        NaN
             354         NaN        NaN        NaN
             370         NaN        NaN        NaN
     62      360         NaN        NaN        NaN
             361    779000.0   918000.0        NaN
             371         NaN        NaN        NaN
             373         NaN        NaN        NaN
             374         NaN        NaN        NaN
             376         NaN        NaN   899000.0
13   54      350     42000.0        NaN    34000.0
             353         NaN        NaN        NaN
             370         NaN        NaN        NaN
     62      360         NaN        NaN        NaN
             361    118000.0   122000.0        NaN
             373         NaN        NaN        NaN
             374         NaN        NaN        NaN
             376         NaN        NaN   138000.0
     A       310         NaN    26000.0        NaN
             317         NaN        NaN        NaN
             332         NaN        NaN     2000.0
             339      6000.0        NaN        NaN
     D       337      2000.0        NaN        NaN
14   62      360         NaN        NaN        NaN
             361     61200.0    68000.0        NaN
             371         NaN        NaN        NaN
             373         NaN        NaN        NaN
             374         NaN        NaN        NaN
             376         NaN        NaN    60050.0
     A       310         NaN   134400.0        NaN
             311         NaN        NaN        NaN
             314         NaN        NaN        NaN
             317         NaN        NaN        NaN
             330         NaN        NaN        NaN
             331         NaN        NaN        NaN
             334         NaN        NaN        NaN
             336         NaN        NaN        NaN
             339    133600.0        NaN   145800.0
     D       312     30000.0    60000.0        NaN
             316         NaN        NaN        NaN
             337         NaN        NaN    39000.0
15   A       310         NaN   281000.0        NaN
             311         NaN        NaN        NaN
             313         NaN        NaN        NaN
             314         NaN        NaN        NaN
             317         NaN        NaN        NaN
             330         NaN        NaN        NaN
             331         NaN        NaN        NaN
             332         NaN        NaN        NaN
             333         NaN        NaN        NaN
             336         NaN        NaN        NaN
             339    300000.0        NaN   265000.0
     D       312     79000.0        NaN    75000.0
             316         NaN        NaN        NaN
             337         NaN    65000.0        NaN
16   54      350    244000.0   230000.0   244000.0
             351         NaN        NaN        NaN
             352         NaN        NaN        NaN
             353         NaN        NaN        NaN
             354         NaN        NaN        NaN
17   62      360     50000.0        NaN        NaN
             361         NaN        NaN        NaN
             373         NaN        NaN        NaN
             374         NaN        NaN        NaN
             376         NaN        NaN   234000.0
     A       310         NaN   121000.0        NaN
             313         NaN        NaN        NaN
             317         NaN        NaN        NaN
             330         NaN        NaN        NaN
             331         NaN        NaN        NaN
             333         NaN        NaN        NaN
             334         NaN        NaN        NaN
             336         NaN        NaN        NaN
             338         NaN        NaN        NaN
             339    283000.0        NaN   300200.0
     D       316         NaN        NaN        NaN
             337         NaN    60000.0    18000.0
18   54      350     14000.0        NaN        NaN
             351         NaN        NaN     8700.0
             352         NaN    28000.0        NaN
             354         NaN        NaN        NaN
             370         NaN        NaN        NaN
     62      360         NaN        NaN        NaN
             361    306400.0   307600.0        NaN
             371         NaN        NaN        NaN
             373         NaN        NaN        NaN
             374         NaN        NaN        NaN
             376         NaN        NaN   271600.0
     A       310         NaN   419700.0        NaN
             311         NaN        NaN        NaN
             313         NaN        NaN        NaN
             314         NaN        NaN        NaN
             317         NaN        NaN        NaN
             330         NaN        NaN        NaN
             331         NaN        NaN        NaN
             332         NaN        NaN        NaN
             333         NaN        NaN        NaN
             334         NaN        NaN        NaN
             336         NaN        NaN        NaN
             338         NaN        NaN        NaN
             339    466400.0        NaN   455500.0
     D       312     52200.0    28000.0        NaN
             316         NaN        NaN        NaN
             337         NaN        NaN    24400.0
19   62      360         NaN        NaN        NaN
             361     96900.0   405400.0        NaN
             373         NaN        NaN        NaN
             376         NaN        NaN    25000.0
     A       310         NaN   399600.0        NaN
             311         NaN        NaN        NaN
             313         NaN        NaN        NaN
             317         NaN        NaN        NaN
             330         NaN        NaN        NaN
             331         NaN        NaN        NaN
             332         NaN        NaN        NaN
             333         NaN        NaN        NaN
             334         NaN        NaN        NaN
             339    407000.0        NaN   285000.0
     D       312     45900.0        NaN    51000.0
             316         NaN        NaN        NaN
             337         NaN    66300.0        NaN
1A   A       310         NaN    60200.0        NaN
             311         NaN        NaN        NaN
             314         NaN        NaN        NaN
             317         NaN        NaN        NaN
             330         NaN        NaN        NaN
             333         NaN        NaN        NaN
             339    193000.0        NaN    41000.0
     D       312      8000.0        NaN    42000.0
             316         NaN        NaN        NaN
             337         NaN    28800.0        NaN
20   54      350     63000.0        NaN        NaN
             352         NaN    38000.0    48000.0
             354         NaN        NaN        NaN
             370         NaN        NaN        NaN
     62      360         NaN        NaN        NaN
             361         NaN    84250.0        NaN
             371         NaN        NaN        NaN
             373         NaN        NaN        NaN
             374     61250.0        NaN        NaN
             376         NaN        NaN    94500.0
2A   62      360         NaN     5000.0        NaN
             361     80000.0        NaN        NaN
             371         NaN        NaN        NaN
             373         NaN        NaN        NaN
             376         NaN        NaN    77000.0

In [188]:
s0 = tickets[['Tank']]
s1 = schedule_1[['Tank']]
s2 = schedule_2[['Tank']]
s3 = schedule_3[['Tank']]
s4 = schedule_4[['Tank']]
s0 = pd.concat([s0, s1, s2, s3, s4])
s0 = s0.groupby(['Tank']).count()

#----------------------------------------------------------------------------
#
#
schedule = tickets
schedule = schedule.loc[(schedule['Cycle'] == 31) & (schedule['Type'] == 'In')]
s_in     = schedule.groupby(['Tank']).agg({'Volume':'sum'})
schedule = tickets
schedule = schedule.loc[(schedule['Cycle'] == 31) & (schedule['Type'] == 'Out')]
s_out    = schedule.groupby(['Tank']).agg({'Volume':'sum'})

m = pd.merge(s0, s_in,  how = "left", on=['Tank'])
m = pd.merge(m,  s_out, how = "left", on=['Tank'])

schedule = tickets
schedule = schedule.loc[(schedule['Cycle'] == 41) & (schedule['Type'] == 'In')]
s_in     = schedule.groupby(['Tank']).agg({'Volume':'sum'})
schedule = tickets
schedule = schedule.loc[(schedule['Cycle'] == 41) & (schedule['Type'] == 'Out')]
s_out    = schedule.groupby(['Tank']).agg({'Volume':'sum'})

m = pd.merge(m, s_in,  how = "left", on=['Tank'])
m = pd.merge(m, s_out, how = "left", on=['Tank'])

schedule = tickets
schedule = schedule.loc[(schedule['Cycle'] == 51) & (schedule['Type'] == 'In')]
s_in     = schedule.groupby(['Tank']).agg({'Volume':'sum'})
schedule = tickets
schedule = schedule.loc[(schedule['Cycle'] == 51) & (schedule['Type'] == 'Out')]
s_out    = schedule.groupby(['Tank']).agg({'Volume':'sum'})

m = pd.merge(m, s_in,  how = "left", on=['Tank'])
m = pd.merge(m, s_out, how = "left", on=['Tank'])

schedule = tickets
schedule = schedule.loc[(schedule['Cycle'] == 61) & (schedule['Type'] == 'In')]
s_in     = schedule.groupby(['Tank']).agg({'Volume':'sum'})
schedule = tickets
schedule = schedule.loc[(schedule['Cycle'] == 61) & (schedule['Type'] == 'Out')]
s_out    = schedule.groupby(['Tank']).agg({'Volume':'sum'})

m = pd.merge(m, s_in,  how = "left", on=['Tank'])
m = pd.merge(m, s_out, how = "left", on=['Tank'])

#----------------------------------------------------------------------------
#
#
def typ(df):
    if (df['Line'] in ['01', '02']):
        return 'In'
    else:
        return 'Out'
schedule_1['Type']    = schedule_1.apply(typ, axis = 1)
schedule_2['Type']    = schedule_2.apply(typ, axis = 1)
schedule_3['Type']    = schedule_3.apply(typ, axis = 1)
schedule_4['Type']    = schedule_4.apply(typ, axis = 1)

schedule = schedule_1
schedule = schedule.loc[(schedule['Type'] == 'In')]
s_in     = schedule.groupby(['Tank']).agg({'Volume':'sum'})
schedule = schedule_1
schedule = schedule.loc[(schedule['Type'] == 'Out')]
s_out    = schedule.groupby(['Tank']).agg({'Volume':'sum'})

m = pd.merge(m, s_in,  how = "left", on=['Tank'])
m = pd.merge(m,  s_out, how = "left", on=['Tank'])

schedule = schedule_2
schedule = schedule.loc[(schedule['Type'] == 'In')]
s_in     = schedule.groupby(['Tank']).agg({'Volume':'sum'})
schedule = schedule_2
schedule = schedule.loc[(schedule['Type'] == 'Out')]
s_out    = schedule.groupby(['Tank']).agg({'Volume':'sum'})

m = pd.merge(m, s_in,  how = "left", on=['Tank'])
m = pd.merge(m,  s_out, how = "left", on=['Tank'])

schedule = schedule_3
schedule = schedule.loc[(schedule['Type'] == 'In')]
s_in     = schedule.groupby(['Tank']).agg({'Volume':'sum'})
schedule = schedule_3
schedule = schedule.loc[(schedule['Type'] == 'Out')]
s_out    = schedule.groupby(['Tank']).agg({'Volume':'sum'})

m = pd.merge(m, s_in,  how = "left", on=['Tank'])
m = pd.merge(m,  s_out, how = "left", on=['Tank'])

schedule = schedule_4
schedule = schedule.loc[(schedule['Type'] == 'In')]
s_in     = schedule.groupby(['Tank']).agg({'Volume':'sum'})
schedule = schedule_4
schedule = schedule.loc[(schedule['Type'] == 'Out')]
s_out    = schedule.groupby(['Tank']).agg({'Volume':'sum'})

m = pd.merge(m, s_in,  how = "left", on=['Tank'])
m = pd.merge(m,  s_out, how = "left", on=['Tank'])

#----------------------------------------------------------------------------
#
#
m.reset_index()
m.to_csv("results/analysis_tanks_3.csv")